version: '3'

services:
  backend:
    image: twentycrm/twenty:v0.50.9
    environment:
      APP_SECRET: $$cap_app_secret
      PG_DATABASE_URL: $$cap_pg_url
      REDIS_URL: $$cap_redis_url
      SERVER_URL: $$cap_server_url
      STORAGE_TYPE: local
    volumes:
      - twenty-local-storage:/app/.local-storage
      - twenty-docker-data:/app/docker-data
    expose:
      - 3000
    networks:
      - twenty-network

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - twenty-network

volumes:
  twenty-local-storage:
  twenty-docker-data:

networks:
  twenty-network:
